name: Version Bump Automation

on:
  pull_request:
    branches: [ master, develop ]
    types: [ closed ]

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          chmod +x ./.github/intall-py-dependecies.sh
          ./.github/intall-py-dependecies.sh
          
      - name: Compute Version
        id: semver
        run: |
          export var=$(python ./.github/bump-version.py $GITHUB_REF)
          vars=($var)
          echo "::set-output name=INTERNALVERSION::${vars[0]}"
          echo "::set-output name=INTERNAL::${vars[1]}"
          echo "::set-output name=EXTERNALVERSION::${vars[2]}"
          echo "::set-output name=EXTERNAL::${vars[3]}"
          echo "::set-output name=INTERNALINTENT::${vars[4]}"
          echo "::set-output name=INTERNALINTENT::${vars[5]}"
          echo "::set-output name=BRANCH::$GITHUB_REF"
        
      - name: Update Version for Internal
        if: ${{steps.semver.outputs.INTERNALVERSION}} != None
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{steps.semver.outputs.INTERNAL}}
          propertyPath: info.version
          value: ${{steps.semver.outputs.INTERNALVERSION}}
          commitChange: true
          updateFile: true
          targetBranch: ${{steps.semver.outputs.BRANCH}}
          masterBranchName: master
          createPR: false
          branch:  ${{steps.semver.outputs.BRANCH}}
          message: Bump version to ${{steps.semver.outputs.INTERNALVERSION}} in ${{steps.semver.outputs.INTERNAL}} with intent ${{steps.semver.outputs.INTERNALINTENT}} 

      - name: Update Version for External
        if: ${{steps.semver.outputs.EXTERNALVERSION}} != None
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{steps.semver.outputs.EXTERNAL}}
          propertyPath: info.version
          value: ${{steps.semver.outputs.EXTERNALVERSION}}
          commitChange: true
          updateFile: true
          targetBranch: ${{steps.semver.outputs.BRANCH}}
          masterBranchName: master
          createPR: false
          branch:  ${{steps.semver.outputs.BRANCH}}
          message: Bump version to ${{steps.semver.outputs.EXTERNALVERSION}} in ${{steps.semver.outputs.EXTERNAL}} with intent ${{steps.semver.outputs.EXTERNALINTENT}} 
